---
title: "data_manipulattion"
output: html_document
---


```{r setup}
## It is a collection of many usefull packages
library(tidyverse)
litters_data = read_csv(file = "./data/FAS_litters.csv")
litters_data = janitor::clean_names(litters_data )

pups_data = read_csv("./data/FAS_pups.csv",col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)


```

### Select function

##Select is about doing with the columns
```{r}
## "pull" 可以输出向量内容
pull(litters_data,group)

## 　However, the "select "can output dataframe
select(litters_data, group, litter_number, gd0_weight, pups_born_alive)

##  从group到gd_of_birth
select(litters_data, group:gd_of_birth)

## 除去pups_survive
select(litters_data, -pups_survive)

## 可以改名, 加选择特定的列at the same time!
select(litters_data, GROUP = group, LiTtEr_NuMbEr = litter_number)

## 也可以直接用rename改名
rename(litters_data, GROUP = group, LiTtEr_NuMbEr = litter_number)

## rerange columns, 可以按照select 里的重新排列
## everything() 其他列保持一样
select(litters_data, litter_number, group, everything())

## 但是litters_data 本身不会改变！除非你重新赋给新表格!!!!!!!!!!
```
### Filter function

## Filter is about raws in columns

## Some logical words

gd_of_birth == 20
pups_born_alive >= 2
pups_survive != 4
!(pups_survive == 4)

group %in% c("Con7", "Con8")
    ("%in%"can filter multiple groups)

group == "Con7" & gd_of_birth == 20

```{r}

## "=" is about assignment
## "==" is about "is XX equals to XX", a logical sentence
filter(litters_data,group=="Con7")

filter(litters_data,gd_of_birth==20)

## "|" is "or"
## hard to debug, not recommand
## use "%in%"!!!!!
filter(litters_data,group=="Con7" | group=="Con8")
filter(litters_data,group %in% c("Con7", "Con8"))

## can filter two variable 有加减乘除
filter(litters_data,gd0_weight + gd18_weight >70)

## don't do this!!!!
filter(litters_data,is.na(gd0_weight))

## remove na
drop_na(litters_data, gd0_weight)
drop_na(litters_data)

```
### mutate function
```{r}
## can add new collmns based on existing columns
## also can modify the existing columns
## "str_to_lower" order a variable from upper to lower
mutate(litters_data,
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group)
)
```

### arrange

## 用来排序
```{r}
## sort the date frame based on pups_born_alive
arrange(litters_data, pups_born_alive)

## can arrange a couple of things
head(arrange(litters_data, group, pups_born_alive), 10)

```

### !!!!!!pipe!!!!!!!!!!

## %>%

# 不用每做一步创建一个新df！！！！！
```{r}
litters_data = 
  read_csv(file = "./data/FAS_litters.csv") %>%
  janitor::clean_names() %>% 
  select(-pups_survive) %>% 
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) %>% 
  drop_na(wt_gain) 
  

```

```{r}
## no more"$"!!!!!!!!!!!!!!!!!
## many powerful functions can be used!!!!!!!!!!
litters_data %>% view()

litters_data %>% pull(gd0_weight)%>%mean
```

```{r}
## dat = . means defaut! equals to "()"
litters_data = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names(dat = .) %>%
  select(.data = ., -pups_survive) %>%
  mutate(.data = .,
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) %>% 
  drop_na(data = ., wt_gain)
```