---
title: "data import"
output: github_document
---

```{r setup}

library(tidyverse)



```
## loading a datatset
```{r}
## reads in a datatset
## 不要用绝对路径！！！
## 不适用其他电脑！！！
## 不要用read。csv， 用read_csv!!!
## don't use "view "inside a Rmarkdown!!! use it in the console
getwd()

litters_data = read_csv(file = "./data/FAS_litters.csv")
litters_data = janitor::clean_names(litters_data )
#install.packages("skimr")
skimr::skim(litters_data)

## double means numbers in compurt, could see the type of data in a column

litters_data = read_csv(file = "./data/FAS_litters.csv",
  skip = 10, col_names = FALSE)


## when the variable contain " ", oftern use "", since the R cannot read tap without "".
litters_data = read_csv(file = "./data/FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)
tail(litters_data)


litters_data = read_csv(file = "./data/FAS_litters.csv",
  col_types = "ccddiiii"
)
litters_data
```

library()
```{r}
library(readxl)
## sheet and range are useful!!!
                        #lb11_data = read_excel("./data/mlb11.xlsx",
                        #sheet="data_sheet",
                        #range="A1:D7")
#head(mlb11_data, 5)
```
```{r}
## data in SAS can also be import in R!!!
#install.packages("haven")
pulse_data = haven::read_sas("./data/public_pulse_data.sas7bdat")

```
```{r}
## do not use "$" to reach a column, use "pull"!!!!
pull(litters_data,"GD0 weight")
```

```{r}
                        lb11_data = read_excel("./data/mlb11.xlsx",
                        #sheet="data_sheet",
                        range="A1:D7")

mlb<-write_csv(lb11_data,path="./data/mlb11.xlsx")
```

